import { shadcn } from "@clerk/themes";

const basePath = import.meta.env.BASE_URL.replace(/\/$/, "");
export const clerkAppearance = {
  theme: shadcn,
  cssLayerName: "clerk",
  options: {
    logoPlacement: "inside" as const,
    logoLinkUrl: basePath || "/",
    logoImageUrl: `${window.location.origin}${basePath}/logo.svg`,
    socialButtonsPlacement: "bottom" as const,
  },
  variables: {
    colorPrimary: "#087443",
    colorForeground: "#183e2b",
    colorMutedForeground: "#52665b",
    colorDanger: "#b42318",
    colorBackground: "#ffffff",
    colorInput: "#ffffff",
    colorInputForeground: "#183e2b",
    colorNeutral: "#52665b",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "0.75rem",
  },
  elements: {
    rootBox: "w-full flex justify-center",
    cardBox: "bg-white rounded-2xl w-[440px] max-w-full overflow-hidden",
    card: "!shadow-none !border-0 !bg-transparent !rounded-none",
    footer: "!shadow-none !border-0 !bg-transparent !rounded-none",
    headerTitle: "text-[#183e2b] font-bold",
    headerSubtitle: "text-[#52665b]",
    socialButtonsBlockButtonText: "text-[#183e2b]",
    formFieldLabel: "text-[#183e2b]",
    footerActionLink: "text-[#087443] font-semibold",
    footerActionText: "text-[#52665b]",
    dividerText: "text-[#52665b]",
    identityPreviewEditButton: "text-[#087443]",
    formFieldSuccessText: "text-[#087443]",
    alertText: "text-[#b42318]",
    logoBox: "justify-center",
    logoImage: "h-16",
    socialButtonsBlockButton: "border border-[#d3dfd7] bg-white",
    formButtonPrimary: "bg-[#087443] text-white",
    formFieldInput: "bg-white text-[#183e2b] border-[#d3dfd7]",
    footerAction: "bg-[#f3f7f4]",
    dividerLine: "bg-[#d3dfd7]",
    alert: "bg-red-50",
    otpCodeFieldInput: "bg-white text-[#183e2b]",
    formFieldRow: "gap-2",
    main: "gap-5",
  },
};